### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by cognitive137**
Created a README.md file.

### CODE REVIEW

**Review by acagastya — CHANGES_REQUESTED** [review]
Thanks for the PR, @cognitive137.

Could you please update the last line of the README?
```diff
- **Note:** In case if your message contains templates and you don't want the bot to announce the link -- add `--nl` at the end of the message.
+ **Note:** In case if you do not want the wikilinks and templates in your message to be be announced by the bot, add `--ignore` at the end of the message.
```

`--nl` was retired in favour of `--ignore` so it is easier to remember.

**Comment by cognitive137** [comment]
Updated.

**Comment by cognitive137** [comment]
Updated.

**Comment by cognitive137** [comment]
Updated.

**Review by acagastya — APPROVED** [review]
Thanks.

**Pull request merged**
